name: repair_app
description: "Home & Office Repair App – report issues, get matched with specialists, and track progress."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.8
  lottie: ^2.2.0
  flutter_typeahead: ^4.6.2
  http: ^1.3.0
  flutter_secure_storage: ^9.0.0 
  image: ^4.1.4
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.json
    - assets/Logo.png
    - assets/plumbing.png
    - assets/electricity.png
    - assets/architecture.png
    - assets/profile_pic.png
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/Lobster-Regular.ttf
